### ISSUE TITLE
Question: understanding the timing of `evalZ3`

### ISSUE THREAD

**Issue by meditans** [IagoAbal/haskell-z3#17]
Hi,
in a current project of mine, I am using z3 to solve a lot of small problems, via `evalZ3 smallProblem`. The typical time for one of these problems, brutally measured using `:set +s` in ghci, is around 0.3s.

Now, I'd like to understand where these 0.3s are spent: are they mainly spent in the z3 solution, or in the z3 process initialization, so that I would benefit from invoking the solver only once and `reset`ting the solver state instead? Most importantly, how can I measure this?

**Comment by IagoAbal** [comment]
Well, `evalZ3` does create a new Z3 context, a new solver, and even a new `Fixedpoint` context (regardless of whether you use it or not). I assume these three initialization steps do take some time. How much of those 0.3s, I honestly don't know because I have never measured it. It's kind of clear that the overhead is going to be more important for small problems.

You can use the slightly lower-level `Z3.Base` API to measure how much those initializations cost. Take a look at [newEnvWith](http://hackage.haskell.org/package/z3-408.0/docs/src/Z3-Monad.html#newEnvWith), this is the function that initializes a Z3 environment. You may find [criterion](http://hackage.haskell.org/package/criterion) useful. 

If you're running lots of small problems then I think using `solverReset` is a good idea, at the very least `mkContext` and `mkSolver` will perform some allocations, and a rule of thumb for performance is to avoid lots of small allocations (isn't it?). Of course, to be sure, one needs to measure the cost of `solverReset`. I would suggest that you try both alternatives compare execution time and memory consumption.

By the way, if you don't need the `Fixedpoint` context, you can create your own `MonadZ3`, it's pretty easy.

Sorry for the delay in replying (you can always ping me by email) and I hope this helps!
