### ISSUE TITLE
Z3 removed Z3_fixpoint_push/pop

### ISSUE THREAD

**Issue by santolucito** [IagoAbal/haskell-z3#22]
https://github.com/Z3Prover/z3/commit/40e329fc92e91acc9efda668e8d6d034221fe887

I'm not sure what the fix is, but Z3 4.8.5 removed these api fxns which can cause problems with the haskell bindings now

**Comment by IagoAbal** [comment]
Hi, thanks for reporting this. It seems that `push` and `pop` operations for fixedpoint objects were not really supported, so they ended up removing them from the API (https://github.com/Z3Prover/z3/issues/2249). The fix is to remove it from the Haskell bindings as well. Could you open a pull request?
